### PR TITLE
Combine 'eventuals' with 'eventuals-grpc'

### PR DESCRIPTION
**Pull request by benh**
We've run into enough frictions making sure that we don't break `eventuals-grpc` that we're going to move it into this repository. This PR does so by maintaining all of the history!

Note that I've removed the requirement for the Windows build to pass because I need some Windows experts to help out with that and I'd like to get this merged ASAP to avoid recreating this PR after other commits are made as there were issues that had to be resolved in order to do the combine.

### CODE REVIEW

**Comment by benh** [comment]
@FolMing @ArthurBandaryk I need my Windows experts! Any idea why the Windows [build](https://github.com/3rdparty/eventuals/runs/5436247406?check_suite_focus=true) is failing?

**Comment by CodingCanuck** [comment]
> @FolMing @ArthurBandaryk I need my Windows experts! Any idea why the Windows [build](https://github.com/3rdparty/eventuals/runs/5436247406?check_suite_focus=true) is failing?

File path too long?

```
 The object file directory

    C:/Users/runneradmin/_bazel_runneradmin/cdhujlpa/execroot/com_github_3rdparty_eventuals/bazel-out/x64_windows-dbg/bin/external/com_github_curl_curl/libcurl_boringssl_windows.build_tmpdir/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_19e7f.dir/./

  has 235 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    CMakeCCompilerABI.c.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.


-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe
CMake Warning in C:/Users/runneradmin/_bazel_runneradmin/cdhujlpa/execroot/com_github_3rdparty_eventuals/bazel-out/x64_windows-dbg/bin/external/com_github_curl_curl/libcurl_boringssl_windows.build_tmpdir/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory

    C:/Users/runneradmin/_bazel_runneradmin/cdhujlpa/execroot/com_github_3rdparty_eventuals/bazel-out/x64_windows-dbg/bin/external/com_github_curl_curl/libcurl_boringssl_windows.build_tmpdir/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_b2f57.dir/./

  has 235 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    testCCompiler.c.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.


-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe - broken
CMake Error at C:/Users/runneradmin/_bazel_runneradmin/cdhujlpa/external/cmake-3.21.0-windows-x86_64/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files/LLVM/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/runneradmin/_bazel_runneradmin/cdhujlpa/execroot/com_github_3rdparty_eventuals/bazel-out/x64_windows-dbg/bin/external/com_github_curl_curl/libcurl_boringssl_windows.build_tmpdir/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:\users\runneradmin\_bazel_runneradmin\cdhujlpa\execroot\com_github_3rdparty_eventuals/external/ninja_1.10.2_win/ninja.exe cmTC_b2f57 && [1/2] Building C object CMakeFiles\cmTC_b2f57.dir\testCCompiler.c.obj

    [2/2] Linking C executable cmTC_b2f57.exe

    FAILED: cmTC_b2f57.exe 
```

So I guess the solution is to increase `CMAKE_OBJECT_PATH_MAX`, but at a glance I'm not sure how to do that

**Comment by FolMing** [comment]
Hey! I'm getting an internet connection on Thursday, so I'll only be able to look into it after that.

It certainly looks like a max path length issue. In my experience, 99% of the time it can be increased without any dangerous consequences. There should be a way to add that variable and its value into the cmake cache.

**Review by onelxj — APPROVED** [review]
LGTM!

**Pull request merged**
