### PR TITLE
Use "e.g.," consistently in README.md

### PR DESCRIPTION
**Pull request by CodingCanuck**
Per your https://github.com/3rdparty/eventuals/pull/168#issuecomment-1000576457 , this is intended to test whether the build-and-test hook will be skipped for markdown actions.

... but I don't expect this to work with my mental model of GitHub PRs: does this PR ~contain the base BR to disable the build-and-test hook? If so, this PR would contain non-.md files (even though this *commit*) does not. (But as discussed today, I don't yet have a great mental model of how GitHub, remote branches, and local branches all interact!)

### CODE REVIEW

**Comment by CodingCanuck** [comment]
> Per your [#168 (comment)](https://github.com/3rdparty/eventuals/pull/168#issuecomment-1000576457) , this is intended to test whether the build-and-test hook will be skipped for markdown actions.
> 
> ... but I don't expect this to work with my mental model of GitHub PRs: does this PR ~contain the base BR to disable the build-and-test hook? If so, this PR would contain non-.md files (even though this _commit_) does not. (But as discussed today, I don't yet have a great mental model of how GitHub, remote branches, and local branches all interact!)

... and it looks like my expectations were wrong (maybe)!

Here's the full set of checks run on this PR (notably, no builds): 
Screen Shot 2021-12-23 at 3 19 27 PM

Compared to the full set of checks run on https://github.com/3rdparty/eventuals/pull/165 (notably, includes builds): 
Screen Shot 2021-12-23 at 3 21 14 PM


(though this might not be an apples-to-apples comparison as I'm comparing checks run when this PR was mailed vs. checks run when the previous PR was merged)

**Comment by FolMing** [comment]
Yep, it works! Making a change to .md files skips the build entirely - that's great!

Can we do the same for our code style check? I don't think we need to run it since we don't change our code, right?

You're getting better and better at git, keep it up!

**Comment by CodingCanuck** [comment]
> Yep, it works! Making a change to .md files skips the build entirely - that's great!
> 
> Can we do the same for our code style check? I don't think we need to run it since we don't change our code, right?

Does code style only apply to non-markdown files, and do we anticipate it remaining that way going forward? (Do we envision applying style rules or automated formatting to markdown files in the future? A quick googling makes me think that clang-format does *not* handle markdown https://clang.llvm.org/docs/ClangFormatStyleOptions.html and I don't see an obvious / ubiquitous markdown autoformatter tool)

> 
> You're getting better and better at git, keep it up!

Thanks so much for your coaching! Much less head-desking with these latest PRs :)

**Comment by CodingCanuck** [comment]
> > Yep, it works! Making a change to .md files skips the build entirely - that's great!
> > Can we do the same for our code style check? I don't think we need to run it since we don't change our code, right?
> 
> Does code style only apply to non-markdown files, and do we anticipate it remaining that way going forward? (Do we envision applying style rules or automated formatting to markdown files in the future? A quick googling makes me think that clang-format does _not_ handle markdown https://clang.llvm.org/docs/ClangFormatStyleOptions.html and I don't see an obvious / ubiquitous markdown autoformatter tool)

Err, please don't respond here: let's move this conversation to https://github.com/3rdparty/eventuals/pull/168

> 
> > You're getting better and better at git, keep it up!
> 
> Thanks so much for your coaching! Much less head-desking with these latest PRs :)

**Comment by CodingCanuck** [comment]
Nikita, do you think this PR is worth merging? If not, I can close it.

**Review by ArthurBandaryk — APPROVED** [review]
LGTM! Great work!

**Review by FolMing — APPROVED** [review]
@CodingCanuck Sure, let's merge it.
But before you merge it into main, please remove the merge commit! (That's a lot of "merges" :) )

**Comment by CodingCanuck** [comment]
> @CodingCanuck Sure, let's merge it. But before you merge it into main, please remove the merge commit! (That's a lot of "merges" :) )

What's the best way to do that? I would've thought that the "squash and merge" auto-merge would've done that, but I'm definitely still learning here :)

**Comment by FolMing** [comment]
> > @CodingCanuck Sure, let's merge it. But before you merge it into main, please remove the merge commit! (That's a lot of "merges" :) )
> 
> What's the best way to do that? I would've thought that the "squash and merge" auto-merge would've done that, but I'm definitely still learning here :)

Here's what I would do:
1. Revert to the HEAD pointing to main.
2. Cherry-pick the commits that we actually care about.
3. Do a force-push.

This way you will get a history without merge commits AND you will be also rebased onto main. It's a bit hacky but this way we can keep the history clean.

**Comment by CodingCanuck** [comment]
> > > @CodingCanuck Sure, let's merge it. But before you merge it into main, please remove the merge commit! (That's a lot of "merges" :) )
> > 
> > 
> > What's the best way to do that? I would've thought that the "squash and merge" auto-merge would've done that, but I'm definitely still learning here :)
> 
> Here's what I would do:
> 
> 1. Revert to the HEAD pointing to main.
> 2. Cherry-pick the commits that we actually care about.
> 3. Do a force-push.
> 
> This way you will get a history without merge commits AND you will be also rebased onto main. It's a bit hacky but this way we can keep the history clean.

Hmm, I was just sitting down at my keyboard to do this, but it looks like the automerge did its thing :/

But good news: automerge rebased my one "real" / non-merge commit onto main, and all of the merge commits were rebased away: 
Screen Shot 2022-01-05 at 1 55 42 PM

This makes me think that:
1) Pressing GitHub's "update branch" button (or whatever it's called) is safe even though it creates merge commits in the PR branch
2) Automerge rebases as needed, or at least the automerge and rebase option that we have configured
3) (no evidence of this in this PR) since we now require linear commits (and this requirement is fixed after previously being broken), automerge will fail if it actually attempts to push merge commits

**Comment by FolMing** [comment]
> > > > @CodingCanuck Sure, let's merge it. But before you merge it into main, please remove the merge commit! (That's a lot of "merges" :) )
> > > 
> > > 
> > > What's the best way to do that? I would've thought that the "squash and merge" auto-merge would've done that, but I'm definitely still learning here :)
> > 
> > 
> > Here's what I would do:
> > 
> > 1. Revert to the HEAD pointing to main.
> > 2. Cherry-pick the commits that we actually care about.
> > 3. Do a force-push.
> > 
> > This way you will get a history without merge commits AND you will be also rebased onto main. It's a bit hacky but this way we can keep the history clean.
> 
> Hmm, I was just sitting down at my keyboard to do this, but it looks like the automerge did its thing :/
> 
> But good news: automerge rebased my one "real" / non-merge commit onto main, and all of the merge commits were rebased away: Screen Shot 2022-01-05 at 1 55 42 PM
> 
> This makes me think that:
> 
> 1. Pressing GitHub's "update branch" button (or whatever it's called) is safe even though it creates merge commits in the PR branch
> 2. Automerge rebases as needed, or at least the automerge and rebase option that we have configured
> 3. (no evidence of this in this PR) since we now require linear commits (and this requirement is fixed after previously being broken), automerge will fail if it actually attempts to push merge commits

Yeah, I get your theory, you're probably right, we can test some of this stuff in our free time just to get a better understanding of what's going on! 👍

**Pull request merged**
