### PR TITLE
Replace bazel with bazelisk

### PR DESCRIPTION
**Pull request by nizamutdinovb**

### CODE REVIEW

**Review by rjhuijsman — APPROVED** [review]
🎉

**Comment by rjhuijsman** [comment]
@nizamutdinovb because the name of the GitHub Actions tests is based on the contents of the `matrix`, and since those changed, I also had to use my organization owner privileges to modify the branch protection rules' list of required tests to have the new names.

... But because of that the contents of this PR are now required for anyone who wants to submit a PR! So I'm going to go ahead and merge the PR for you straight away. 👍🏻

**Comment by rjhuijsman** [comment]
Hmm, looks like Mergequeue doesn't like the broken windows test that we don't care about right now. Will merge manually.

**Comment by nizamutdinovb** [comment]
> @nizamutdinovb because the name of the GitHub Actions tests is based on the contents of the `matrix`, and since those changed, I also had to use my organization owner privileges to modify the branch protection rules' list of required tests to have the new names.
> 
> ... But because of that the contents of this PR are now required for anyone who wants to submit a PR! So I'm going to go ahead and merge the PR for you straight away. 👍🏻

Thanks @rjhuijsman

**Pull request merged**
