### PR TITLE
Stop skipping builds for markdown changes

### PR DESCRIPTION
**Pull request by CodingCanuck**
I still love the idea of shedding unnecessary build load and avoiding
unnecessary merge latency, but the implementation I submitted is quite
brittle:
Mergequeue queued forever

Waiting for tests before merging is much less painful now that we're
using mergequeue, so let's remove the nobuilds to keep merging simple
and robust (though not as fast as might be ideal).

### CODE REVIEW

**Review by benh — APPROVED** [review]

**Comment by benh** [comment]
@ArthurBandaryk @CodingCanuck any other repos we need to do this to?

**Comment by CodingCanuck** [comment]
> @ArthurBandaryk @CodingCanuck any other repos we need to do this to?

Just Respect, I think: https://github.com/reboot-dev/respect/pull/294

**Comment by CodingCanuck** [comment]
> > > @ArthurBandaryk @CodingCanuck any other repos we need to do this to?
> > 
> > 
> > Just Respect, I think: [reboot-dev/respect#294](https://github.com/reboot-dev/respect/pull/294)
> 
> I spy one in [stout](https://github.com/3rdparty/stout/blob/master/.github/workflows/nobuild.yml?rgh-link-date=2022-04-06T15%3A27%3A15Z) too, please give a look at the rest of the repos you've worked in @ArthurBandaryk, thank you!

Oops, good catch! I only did a local search in repos I had cloned: let's do a more exhaustive search.

Under reboot-dev, I also missed one under respect-integration: https://github.com/search?q=org%3Areboot-dev+filename%3Anobuild but I guess we don't care about that because we're turning that down.

Under 3rdparty, ditto for eventuals-grpc: https://github.com/search?q=org%3A3rdparty+filename%3Anobuild

So I think we only need to change eventuals, stout, and respect.

**Comment by CodingCanuck** [comment]
> > > > @ArthurBandaryk @CodingCanuck any other repos we need to do this to?
> > > 
> > > 
> > > Just Respect, I think: [reboot-dev/respect#294](https://github.com/reboot-dev/respect/pull/294)
> > 
> > 
> > I spy one in [stout](https://github.com/3rdparty/stout/blob/master/.github/workflows/nobuild.yml?rgh-link-date=2022-04-06T15%3A30%3A56Z) too, please give a look at the rest of the repos you've worked in @ArthurBandaryk, thank you!
> 
> Oops, good catch! I only did a local search in repos I had cloned: let's do a more exhaustive search.
> 
> Under reboot-dev, I also missed one under respect-integration: [github.com/search?q=org%3Areboot-dev+filename%3Anobuild](https://github.com/search?q=org%3Areboot-dev+filename%3Anobuild) but I guess we don't care about that because we're turning that down.
> 
> Under 3rdparty, ditto for eventuals-grpc: [github.com/search?q=org%3A3rdparty+filename%3Anobuild](https://github.com/search?q=org%3A3rdparty+filename%3Anobuild)
> 
> So I think we only need to change eventuals, stout, and respect.

PR to remove this pattern from stout: https://github.com/3rdparty/stout/pull/25

**Pull request merged**
